runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

env_variables:
  GCP_PROJECT: "speech-test-471607"
  SMTP_USERNAME: "drabhijeet@muktanganfoundation.org"
  SMTP_PASSWORD: "Abhijeet@2025"

automatic_scaling:
  max_instances: 1
  min_instances: 0

instance_class: F1

handlers:
  # Serve HTML files from root
  - url: /(.*\.html)
    static_files: \1
    upload: (.*\.html)

  # Serve CSS files from root
  - url: /(.*\.css)
    static_files: \1
    upload: (.*\.css)

  # Serve JS files from root
  - url: /(.*\.js)
    static_files: \1
    upload: (.*\.js)
